feed_url: <%= ENV['FEED_URL'] %>

notifications:
  email:
    sendgrid_api_key: <%= ENV['SENDGRID_API_KEY'] %>
    from: <%= ENV['FROM_EMAIL'] %>
    database_url: <%= ENV['DATABASE_URL'] %>
  twitter:
    consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>
    access_token: <%= ENV['TWITTER_ACCESS_TOKEN'] %>
    access_token_secret: <%= ENV['TWITTER_ACCESS_TOKEN_SECRET'] %>
